Make the output of the dot format deterministic and stable
tox-dev/pipdeptree pull request #189
Opened 2023-01-09 15:34 UTC by kdeldycke

Fixes https://github.com/tox-dev/pipdeptree/issues/188

2023-02-05 21:54 UTC, gaborbernat requested changes
Fix CI, rebase on main and add test.

2023-02-17 11:36 UTC, kdeldycke commented
Just rebased, squashed, fixed and added unit-tests to ensure stability of Graphviz output.

All tests are passing, this PR is ready to be merged upstream.

2023-02-17 15:31 UTC, gaborbernat approved these changes

2023-02-17 15:31 UTC, merged

2023-02-18 03:36 UTC, kdeldycke commented
Thanks @gaborbernat for the merge!