precommit: enable codespell
tox-dev/pipdeptree pull request #291
Opened 2023-09-28 00:14 UTC by Borda

it helps to find typos, and in fact, it found one, so fixing it also... :chipmunk:

2023-09-28 05:26 UTC, gaborbernat requested changes
Fix merge conflict.

2023-09-28 06:10 UTC, Borda commented
> Fix merge conflict.

done

2023-09-28 16:09 UTC, gaborbernat approved these changes
![](https://media.tenor.co/images/881314d317f9aa4ccd6ef6c0bd0fe1c5/tenor.gif)

2023-09-28 16:09 UTC, merged

2023-10-04 09:23 UTC, zu-github commented
###