Handle invalid requirement strings when using importlib.metadata
tox-dev/pipdeptree pull request #345
Opened 2024-04-05 19:56 UTC by kemzeb

Resolves #344.

This change also:
- Makes `Distribution.requires()` into a generator for performance (i.e. avoid building `list[Requirement]` and then iterating `list[Requirement` and instead do both at the same time) and so that we can handle invalid requirement exceptions in `PackageDAG.from_pkgs()` for each individual requirement string
- Modified conftest to avoid adding a extra comma at the end and removed some older code

2024-04-05 19:59 UTC, kemzeb commented on src/pipdeptree/_models/dag.py
> +    print("-" * 72, file=sys.stderr)  # noqa: T201
I feel like we have been duplicating the print warning logic across quite a few areas of the codebase. I think we should ponder a better way of handling this in the future

2024-04-05 20:02 UTC, gaborbernat requested changes

2024-04-05 20:02 UTC, gaborbernat commented on src/pipdeptree/_models/dag.py
> +                    # We can't work with invalid requirement strings. Let's warn the user about
This should be aligned for 120 characters. This applies to all other comments too.

2024-04-05 20:02 UTC, kemzeb commented
Here's an example of what it looks like:
```console
$ pipdeptree
Warning!!! Invalid requirement strings found for the following distributions:
catalyst
  Skipping "scikit-image (<0.19.0>=0.16.1) ; extra == 'all'"
------------------------------------------------------------------------
catalyst==22.4
├── accelerate [required: >=0.5.1, installed: 0.29.1]
│   ├── huggingface-hub [required: Any, installed: 0.22.2]
│   │   ├── filelock [required: Any, installed: 3.13.3]
. . .
```

2024-04-06 14:09 UTC, gaborbernat approved these changes

2024-04-06 14:09 UTC, merged